title: "The Subtle Art of Building a three-tier application using Docker"
author: "Virendrasinh Khuman"
description: "In this tutorial, we'll walk through setting up a three-tier application using Docker. We'll create a multi-container setup consisting of a presentation tier (front end), an application tier (back end), and a data tier (database)." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "virendrasinhkhuman@gmail.com"
twitter_username: "VirendrasinhKh4"
github_username: "virendrasinh734"
linkedin_username: "virendrasinh-khuman"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
